# web-controller.yml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: containerdemo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: containerdemo
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
        - image: MY_IMAGE
          name: containerdemo
          ports:
            - containerPort: 3000
              name: http-server
